# Generated by Django 2.2.2 on 2019-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.CharField(blank=True, choices=[('hp', 'harry potter'), ('p', 'python'), ('a', 'alice')], max_length=30, null=True, verbose_name='books'),
        ),
    ]
