# Generated by Django 2.2.2 on 2019-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_book_sectionn_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='books',
        ),
        migrations.RemoveField(
            model_name='library',
            name='book',
        ),
        migrations.RemoveField(
            model_name='library',
            name='sut',
        ),
        migrations.RemoveField(
            model_name='library',
            name='time',
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(null=True, to='home.Book'),
        ),
        migrations.AddField(
            model_name='library',
            name='libraby_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Library'),
        ),
    ]
