# Generated by Django 2.2.2 on 2019-07-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190702_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='book',
        ),
    ]
